name: 'phillipadsmith.com re-loaded for 2014'
# Also used in the RSS plugin
url: 'http://www.phillipadsmith.com' 
description: "Veteran digital publishing consultant, online advocacy specialist, and strategic convener." 
author: 'Phillip Smith' 
copyright: 'Copyleft 2014' 
tagline: "Pushing bits since '96"
mode: 'development'
markdown: 'kramdown'
pygments: true
# excerpt_separator: "\n\n" TODO Fix excepts on old posts
permalink: /:year/:month/:title.html
exclude: 
    - 'ui/less'
    - '**.less'
    - 'node_modules'
    - 'package.json'
    - 'Gruntfile.js'
    - 'bower.json'
    - '*.cs'
    - 'Gemfile*'
    - 'IDEAS.md'
tag_archive:
    layout: archive_tag
    path: /tag/ 
category_archive:
    layout: archive_category
fbadmins:
    - 511961152
img_lrg: '/ui/img/phillipadsmith-500x500.jpg'
prose:
  rooturl: '_posts'
  siteurl: 'http://phillipadsmith.com'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'files'
  ignore:
    - index.md
    - index.html
    - _config.yml
    - /_layouts
    - /_includes
    - .gitignore
    - .ruby-version
    - 404.html
  metadata:
    _posts:
    - name: "layout"
      field:
        element: "hidden"
        value: "post"
    - name:
      field:
          element: "text"
          label: "Post date"
          value: CURRENT_DATETIME
    - name: "dek"
      field:
        element: "text"
        label: "Dek"
    - name: "summary"
      field:
        element: "text"
        label: "Summary"
    - name: "title"
      field:
        element: "text"
        label: "title"
    - name: "category"
      field:
        element: "select"
        label: "Add Category"
        placeholder: "Choose Category"
        options:
          - name: "Coding"
            value: "coding"
          - name: "Convening"
            value: "convening"
          - name: "Consulting"
            value: "consulting"
          - name: "Covering"
            value: "covering"
          - name: "Commentary"
            value: "commentary"
    - name: "tags"
      field:
        element: "multiselect"
        alterable: "true"
        label: "Add Tags"
        placeholder: "Choose Tags"
        options:
          - name: "Front Page"
            value: "frontpage"
          - name: "Static News Apps"
            value: "staticnewsapps"
          - name: "News Tech Stacks"
            value: "newsteckstacks"
          - name: "The Tyee"
            value: "thetyee"
          - name: "Journalism"
            value: "journalism"
    - name: "img_opt"
      field:
        element: "select"
        label: "Image type"
        placeholder: "Choose type"
        options:
          - name: "Cover"
            value: "cover"
          - name: "Inline"
            value: "inline"
          - name: "None"
            value: "none"
    - name: "img_sml"
      field:
        element: "text"
        label: "Small image (320x256)"
    - name: "img_med"
      field:
        element: "text"
        label: "Med image (640x512)"
    - name: "img_lrg"
      field:
        element: "text"
        label: "Large image (800x640)"
    - name: "img_xlg"
      field:
        element: "text"
        label: "XL image (1200x960)"
    - name: "img_alt"
      field:
        element: "text"
        label: "Alt text"
    - name: "img_caption"
      field:
        element: "text"
        label: "Caption"
    - name: "img_url"
      field:
        element: "text"
        label: "URL"
